openapi: 3.0.1
info:
  title: 'f5challange'
  description: 'f5challange'
  version: '2.5.0'
servers:
  - url: http://challange3.appsjamar.com
paths:
  /cache/:
    get:
      tags:
        - test_cache
      description: tj_int
      operationId: tj_int
      parameters:
        - name: tj
          in: query
          required: true
          allowEmptyValue: false
          schema:
            type: integer
      responses:
        200:
          description: OK
        404:
          description: NotFound
  /normal/:
    get:
      tags:
        - test_cache
      description: tj_int
      operationId: tj_int2
      parameters:
        - name: tj
          in: query
          required: true
          allowEmptyValue: false
          schema:
            type: integer
      responses:
        200:
          description: OK
        404:
          description: NotFound
